version: '3'
services:
  app-web:
    image: app:app-web
    container_name: app-web
    build: .
    ports:
      - "8000:80"
    working_dir: '/var/www/html'
    volumes:
      - ./app:/var/www/html