<html>
    <head>
        <script type="text/javascript" src="http://172.27.92.10/javascripts/api/tableau-2.min.js">
        </script>
        <script type="text/javascript">
            var workbook, activeSheet;
            var tabs =["Metrics Dashboard","NPS Dashboard","Metric Selected Dashboard"];
            var viz;

            function initViz() {
                console.log("test");
                var width = window.screen.width;
                var height = window.screen.height;

                var containerDiv = document.getElementById("vizContainer"),
                    url = "http://172.27.92.10/t/OperationalDashboards/views/TVDashboard-Product/MetricSelectedDashboard";

                var options = {

                    width: width,
                    height: height,
                    marginLeft: "0px",
                    marginRight: "0px",
                    paddingLeft: "0px",
                    paddingRight: "0px",
                    hideTabs: false,
                    hideToolbar: false,
                    onFirstInteractive: function () {
                        workbook = viz.getWorkbook();
                        activeSheet = workbook.getActiveSheet();
                    }
                };

                viz = new tableau.Viz(containerDiv, url, options);
            }

            function sleep(milliseconds) {
                var start = new Date().getTime();
                for (var i = 0; i < 1e8; i++) {
                    if ((new Date().getTime() - start) > milliseconds){
                        break;
                    }
                }
            }

            function switchToMapTab(i) {
                if(i <= tabs.length-1 && i >= 0) {
                    console.log("start");
                    console.log(tabs[i]);
                    workbook.activateSheetAsync(tabs[i]);
                    console.log("wait");
                    sleep(10000);
                    console.log("done");
                }
            }

            function changeTabs() {
                var i = 0;
                var y = 1;
                switchToMapTab(i);
                viz.show();
                switchToMapTab(y);
            }
        </script>
    </head>
    <body onload="initViz();">
        <div class="vizContainer"></div>
    </body>
</html>
